n_of_attributes = 4 + 3 + 3
n_of_values = 4
import numpy as np


def generate_users(N):
    users = {}
    for i in range(N):
        
        users['AutoGenerated{}'.format(i)] = [[np.random.normal(0, 0.5, 1)[0],np.random.normal(6,0.5,1)[0]] 
                                              for i in range(n_of_attributes*n_of_values)]
    return users