import numpy as np
import uuid
import random
n_of_attributes = 4 + 3 + 3
n_of_values = 4


def generate_users(N):
    users = {}
    for i in range(N):

        params = [[np.random.normal(0, 0.5, 1)[0], np.random.normal(
            6, 0.5, 1)[0]] for i in range(n_of_attributes*n_of_values)]

        users['AutoGenerated{}'.format(i)] = (
            [params, 0], uuid.uuid4().hex, random.randint(0, 1))

    return users
