# Generated by Django 3.0.3 on 2020-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200322_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(),
        ),
    ]
