# Generated by Django 3.0.3 on 2020-03-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20200322_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='number',
        ),
    ]
