# Generated by Django 2.2.7 on 2020-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_remove_classes_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='description',
        ),
        migrations.AlterField(
            model_name='classes',
            name='materials',
            field=models.ManyToManyField(related_name='classes', to='app.Material'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
