# Generated by Django 2.2.7 on 2020-07-22 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_classes_activestudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='activeStudents',
            field=models.ManyToManyField(related_name='confirmed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
