# Generated by Django 2.2.7 on 2019-11-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_jsonparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='parameters',
        ),
    ]
