# Generated by Django 2.2.7 on 2019-11-09 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191109_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('IDKparam', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
