# Generated by Django 2.2.7 on 2019-11-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191109_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='displayName',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
