# Generated by Django 2.2.7 on 2019-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_material_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userHash',
            field=models.CharField(default='bla', max_length=100),
            preserve_default=False,
        ),
    ]
