# Generated by Django 2.2.7 on 2019-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userinfo_userhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
