# Generated by Django 2.2.7 on 2019-11-25 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='IDKparam',
        ),
        migrations.AlterField(
            model_name='visit',
            name='timeOfVisit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
