# Generated by Django 2.2.7 on 2020-02-02 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191125_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userHash',
            field=models.CharField(default='c3184df14203412d9415f02b7fda560e', max_length=100),
        ),
    ]
