# Generated by Django 2.2.7 on 2020-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200202_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userHash',
            field=models.CharField(default='dd60ec8d3f4f4a388673b52d4a6e7591', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]
