# Generated by Django 2.2.7 on 2020-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200202_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userHash',
            field=models.CharField(default='ee0dd575649848649ccb4d177c06525c', max_length=100),
        ),
    ]
