# Generated by Django 3.0.3 on 2020-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200322_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='displayName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
