# Generated by Django 2.2.7 on 2020-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200322_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
